config/routes.rb
Rails.application.routes.draw do
  root 'plants#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :plants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
# == Schema Information
#
# Table name: plants
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  notes      :text
#  water      :datetime
#  private    :boolean          default("true"), not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Plant < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :keeper,
    class_name: :User,
    foreign_key: :user_id

  has_many_attached :images
  scope :with_eager_loaded_images, -> { eager_load(images_attachments: :blog) }

  def last_watered
    if water
      time_ago_in_words(water)
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: { message: 'Password cannot be blank.' }

  attr_reader :password

  before_validation :ensure_session_token
  
  has_many :plants

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token

    while User.exists?(session_token: self.session_token)
      self.session_token = self.class.generate_session_token
    end
    self.save!

    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(new_pw)
    @password = new_pw
    self.password_digest = BCrypt::Password.create(new_pw)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :current_user_id, :current_user_username

  private 

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_user_id
    current_user ? current_user.id : nil
  end

  def current_user_username
    current_user ? current_user.username : nil
  end

  def require_current_user!
    redirect_to new_session_url unless current_user
  end

  def require_no_current_user!
    redirect_to root_url if current_user
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :require_current_user!, except: [:index]
  before_action :require_owner!, only: [:edit, :update, :destroy]

  def index
    @plants = Plant.with_attached_images
  end

  def show
    find_plant_by_params_id
    
    if @plant
      render :show
    else
      render :index
    end
  end
  
  def new
    @plant = Plant.new
  end

  def create
    @plant = current_user.plants.new(plant_params)

    if @plant.save
      flash[:notices] = ["Plant saved!"]
      redirect_to plant_url(@plant)
    else
      flash.now[:errors] = @plant.errors.full_messages
      render :new
    end
  end

  def edit
    find_plant_by_params_id
  end

  def update
    find_plant_by_params_id

    if @plant.update_attributes(plant_params)
      flash[:notices] = ['Plant updated!']
      if request.referer == edit_plant_url(@plant)
        redirect_to @plant
      else
        redirect_to request.referer
      end
    else
      flash[:errors] = @plant.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_plant_by_params_id

    if @plant.destroy
      flash[:notices] = ['Plant deleted!']
      redirect_to user_url(current_user_id)
    else
      flash[:errors] = @plant.errors.full_messages
      render plant_url(@plant)
    end
  end


  private

  def plant_params
    params.require(:plant).permit(:name, :notes, :water, :private, :user_id, images: [])
  end

  def find_plant_by_params_id
    @plant = Plant.find_by(id: params[:id])
  end

  def require_owner!
    redirect_to new_session_url unless current_user_id == find_plant_by_params_id.user_id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    credentials = [user_params[:username], user_params[:password]]
    @user = User.find_by_credentials(*credentials)

    if @user
      login!(@user)
      flash[:notices] = ["Welcome #{@user.username}!"]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['Invalid credentials']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    find_user_by_params_id

    if @user
      render :show
    else
      render :index
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      flash[:notices] = ["You have successfully signed up!"]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def find_user_by_params_id
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keeper of the Grove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <h1>Keeper of the Grove</h1>
    
    <% if flash[:notices] %>
      <% flash[:notices].each do |notice| %>
        <p><b><%= notice %></b></p>
      <% end %>
    <% end %>

    <% if logged_in? %>
      <%= link_to current_user.username, user_url(current_user) %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="form_authenticity_token">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out">
      </form>
    <% else %>
      <p><%= link_to 'Sign Up', new_user_url %></p>
      <p><%= link_to 'Log In', new_session_url %></p>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/plants/_plant_form.html.erb
<% action = (action_type == :new) ? plants_url : plant_url(plant) %>
<% button_text = (action_type == :new) ? "New Plant" : "Update Plant" %>

<%= render 'shared/errors' %>

<form action="<%= action %>" method="POST" enctype="multipart/form-data">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action_type == :edit %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <label>Name: 
    <input type="text" name="plant[name]" value="<%= plant.name %>">
  </label>
  <br>

  <label>Last Watered: 
    <input type="date" name="plant[water]" value="<%= plant.water %>">
  </label>
  <br>

  <label>Notes:
    <textarea name="plant[notes]"><%= plant.notes %></textarea>
  </label>
  <br>

  <label>Private: 
    <input type="radio" name="plant[private]" value=true <%= plant.private == true ? "checked" : "" %>>
  </label>
  <label>Public: 
    <input type="radio" name="plant[private]" value=false <%= plant.private == false ? "checked" : "" %>>
  </label>
  <br>

  <label> Images: 
    <input type="file" name="plant[images][]" multiple="multiple" accept="image/jpeg,image/gif,image/png"> 
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/plants/edit.html.erb
<h2>Edit Plant</h2>

<%= render "plant_form", action_type: :edit, plant: @plant %>

app/views/plants/index.html.erb
<h2>Plants</h2>

<ul>
  <% @plants.each do |plant| %>
    <% if !(plant.private) %>
      <li>
        <a href="<%= user_url(plant.user_id) %>"><%= plant.name %></a>
        <% if plant.images.attached? %>
          <p>
            <% plant.images.each do |image| %>
              <%= image_tag(image) %>
            <% end %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/plants/new.html.erb
<h2>New Plant</h2>

<%= render "plant_form", action_type: :new, plant: @plant %>

app/views/plants/show.html.erb
<h2><%= @plant.name %></h2>

<% if @plant.last_watered %>
  <p><i><%= @plant.last_watered %></i></p>
<% end %>

<% if @plant.notes %>
  <p><%= @plant.notes %></p>
<% end %>

<% if @plant.images.attached? %>
  <p>
    <% @plant.images.each do |image| %>
      <%= image_tag(image) %>
    <% end %>
  </p>
<% end %>


<form action="<%= plant_url(@plant) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Plant">
</form>

<p><a href="<%= edit_plant_url(@plant) %>">Edit Plant</a></p>
<p><a href="<%= user_url(current_user_id) %>">All My Plants</a></p>

app/views/shared/_errors.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li><b><%= error %></b></li>
    <% end %>
  </ul>
<% end %>

app/views/users/index.html.erb
<h2>Keepers</h2>

<% @users.each do |user| %>
  <a href="<%= user_url(user) %>"><%= user.username %></a>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render 'shared/errors' %>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Username: 
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <br>
  
  <label>Email: 
    <input type="email" name="user[email]" value="<%= @user.email %>"> 
  </label>
  <br>

  <label>Password: 
    <input type="password" name="user[password]"> 
  </label>
  <br>

  <input type="submit" value="Sign Up"> 
</form>
<br>

<a href="<%= new_session_url %>">Log In!</a>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Plants</h2>

<div class="user-plants">
  <ul>
    <% @user.plants.each do |plant| %>
      <% if plant.images.attached? %>
        <p>
          <% plant.images.each do |image| %>
            <%= image_tag(image) %>
          <% end %>
        </p>
      <% end %>

      <% if @user.id != current_user_id && !(plant.private) %>
        <li>
          <%= plant.name %>
        </li>
      <% end %>
      
      <% if @user.id == current_user_id %>
        <li>
          <a href="<%= plant_url(plant) %>"><%= plant.name %></a>
          <i>watered <%= plant.last_watered %> ago</i>
        </li>
      <% end %>
    <% end %>
  </ul>

  <% if @user == current_user %>
    <p><%= link_to 'New Plant', new_plant_url %></p>
  <% end %>
</div>

<div class="all-plants">
  <p><%= link_to 'Browse Plants', plants_url %></p>
</div>